"""Which document set the app treats as "the corpus".

The corpus is a Python module holding a list of document dicts — generated by
``scripts/corpus/build_cmmi_corpus.py`` for the bundled demo, or by
``scripts/ingest.py`` when you point the system at your own documents.

Everything that reads documents goes through here rather than importing
``data.cmmi_docs`` directly, so swapping in your own corpus is one setting
(``corpus.module`` in config.yaml) instead of an edit in three service files.
Retrieval is switched separately, by ``retrieval.collection`` — they are two
different things: the Qdrant collection is what the *assistant* searches, while
this module is what the *Compliance Checker* checks and what traceability rules
resolve references against.

Both loaders fail soft and return [] when the module is missing or malformed:
the checker reporting "no documents" is a better failure than the API refusing
to start.
"""
from __future__ import annotations

import importlib
import os
from typing import List

# Module paths, importable from the backend/ root. Overridable so a custom corpus
# needs no code change — see _KEY_TO_ENV in backend/config.py.
CORPUS_MODULE = os.getenv("CORPUS_MODULE", "data.cmmi_docs")
DRAFTS_MODULE = os.getenv("DRAFTS_MODULE", "data.cmmi_drafts")

# Attribute names a corpus module may use for its document list. The bundled
# corpus uses the first two; scripts/ingest.py writes `documents`, so its output
# is usable as a corpus module with no renaming.
_CANDIDATE_ATTRS = ("cmmi_documents", "documents", "draft_documents", "sample_documents")


def _load_documents(module_path: str) -> List[dict]:
    """Import ``module_path`` and return the document list it exposes."""
    if not module_path:
        return []
    try:
        module = importlib.import_module(module_path)
    except Exception as exc:  # missing or broken module — degrade, don't crash
        print(f"[corpus] '{module_path}' yüklenemedi / could not be loaded: {exc}", flush=True)
        return []

    for attr in _CANDIDATE_ATTRS:
        value = getattr(module, attr, None)
        if isinstance(value, list):
            return value
    # Fall back to any module-level list of dicts, so a corpus module that named
    # its list something else still works rather than silently coming back empty.
    for name, value in vars(module).items():
        if not name.startswith("_") and isinstance(value, list) and value and isinstance(value[0], dict):
            return value
    print(f"[corpus] '{module_path}' has no document list", flush=True)
    return []


def corpus_documents() -> List[dict]:
    """The documents the checker checks and traceability resolves against."""
    return _load_documents(CORPUS_MODULE)


def draft_documents() -> List[dict]:
    """Deliberately incomplete drafts, if the configured set provides any.

    Test material for the Compliance Checker; never indexed for retrieval. A
    custom corpus normally has none, which is fine — the list is simply empty.
    """
    return _load_documents(DRAFTS_MODULE)
