#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Extract the deliberately INCOMPLETE draft documents (data/CMMI_drafts/*.docx)
into a curated Python module: backend/data/cmmi_drafts.py

These are NOT part of the searchable RAG corpus (backend/data/cmmi_docs.py) and
are never indexed into Qdrant — they exist purely as test material for the
Compliance Checker (Week-4/5): documents that intentionally violate several
rules so a check produces a realistic mix of pass / violation / missing.

Flattening reuses build_cmmi_corpus.extract_text (same paragraphs-as-lines,
table-rows-as ' | '-joined-cells shape as the real corpus), so a draft is judged
exactly like a published document would be.

Re-run after (re)authoring a draft (e.g. scripts/populate/make_draft_srs.py):
    .venv/bin/python scripts/corpus/build_drafts_corpus.py
"""
import os

from build_cmmi_corpus import extract_text

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DRAFTS_DIR = os.path.join(ROOT, "data", "CMMI_drafts")
OUT_PATH = os.path.join(ROOT, "backend", "data", "cmmi_drafts.py")

# Per-draft metadata. doc_kind binds the draft to a rule set (backend/rules/*.yaml);
# version is intentionally a 0.x draft so the baseline-version rule (META-005) fires.
DRAFTS = {
    "CMMI-IT-005_SRS_incomplete.docx": {
        "id": "CMMI-IT-005-DRAFT",
        "doc_kind": "SRS",
        "title": "Sistem Gereksinim Spesifikasyonu (SRS) - Mobil Self-Servis (TASLAK)",
        "department": "Mühendislik",
        "document_type": "procedure",
        "version": "0.9",
        "author": "Kişi 6",
        "created_date": "2025-03-10",
        "language": "TR",
        "tags": ["cmmi", "srs", "taslak", "draft", "sistem gereksinimi", "mobil self-servis"],
    },
    "CMMI-IT-005_SRS_content_gaps.docx": {
        "id": "CMMI-IT-005-DRAFT-B",
        "doc_kind": "SRS",
        "title": "Sistem Gereksinim Spesifikasyonu (SRS) - Mobil Self-Servis (TASLAK — içerik boşlukları)",
        "department": "Mühendislik",
        "document_type": "procedure",
        "version": "0.9",
        "author": "Kişi 1",
        "created_date": "2025-03-14",
        "language": "TR",
        "tags": ["cmmi", "srs", "taslak", "draft", "içerik", "mobil self-servis"],
    },
    "CMMI-IT-005_SRS_skeleton.docx": {
        "id": "CMMI-IT-005-DRAFT-C",
        "doc_kind": "SRS",
        "title": "Sistem Gereksinim Spesifikasyonu (SRS) - Mobil Self-Servis (TASLAK — iskelet)",
        "department": "Mühendislik",
        "document_type": "procedure",
        "version": "0.1",
        "author": "Kişi 1",
        "created_date": "2025-03-08",
        "language": "TR",
        "tags": ["cmmi", "srs", "taslak", "draft", "iskelet", "mobil self-servis"],
    },
}

# Stable ordering (extend as more drafts are added).
ORDER = [
    "CMMI-IT-005_SRS_incomplete.docx",
    "CMMI-IT-005_SRS_content_gaps.docx",
    "CMMI-IT-005_SRS_skeleton.docx",
]

STATUS = "draft"


def main():
    docs = []
    for fn in ORDER:
        path = os.path.join(DRAFTS_DIR, fn)
        if not os.path.exists(path):
            raise FileNotFoundError(f"{fn} not found under {DRAFTS_DIR}")
        meta = DRAFTS[fn]
        content = extract_text(path)
        content = f"{meta['title']}\n{content}"
        docs.append({
            "id": meta["id"],
            "doc_kind": meta["doc_kind"],
            "title": meta["title"],
            "department": meta["department"],
            "document_type": meta["document_type"],
            "status": STATUS,
            "version": meta["version"],
            "author": meta["author"],
            "created_date": meta["created_date"],
            "language": meta["language"],
            "tags": meta["tags"],
            "content": content,
            "is_draft": True,
            "source_file": f"data/CMMI_drafts/{fn}",
        })

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write('"""Auto-generated by scripts/corpus/build_drafts_corpus.py — do not edit by hand.\n\n')
        f.write("Deliberately incomplete DRAFT documents used only as Compliance-Checker test\n")
        f.write('material. NOT part of the searchable RAG corpus and never indexed into Qdrant."""\n\n')
        f.write("draft_documents = [\n")
        for doc in docs:
            f.write("    {\n")
            for key in ["id", "doc_kind", "title", "department", "document_type", "status",
                        "version", "author", "created_date", "language",
                        "tags", "content", "is_draft", "source_file"]:
                f.write(f"        {key!r}: {doc[key]!r},\n")
            f.write("    },\n")
        f.write("]\n")

    print(f"Wrote {len(docs)} draft document(s) to {OUT_PATH}")
    for d in docs:
        print(f"  {d['id']:18s} {d['doc_kind']:6s} {len(d['content']):5d} chars  {d['title']}")


if __name__ == "__main__":
    main()
